fs:
  image: tianon/true
  volumes:
    - ./nginx-html:/usr/share/nginx/html:rw
    - ./nginx-conf:/etc/nginx/conf.d:rw
    - ./nginx-certs:/etc/nginx/ssl:rw
    - ./nginx-logs:/etc/nginx/logs:rw

ui:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - fs
